#!/usr/bin/env python3
# Author: Abigail Shockey
# email: abigail.shockey@slh.wisc.edu
# description: Bacterial genome assembly and AR gene identification pipeline

import subprocess as sub
import sys,os,argparse
import docker
import signal
import multiprocessing as mp
from shutil import copyfile

# local libraries
from app.lib import cpu_count,checkexists
from app.lib import StatusTracker as ST
from app.runPipeline import spriggan_pipeline

# setup signal handler
def handler(sig,frame):
    print('\nShutting down the running docker containers and exiting...')
    client = docker.from_env()
    container_list = client.containers.list(filters={'label':'prog=spriggan'})
    for container in container_list:
        print('shutting down container: ',container.name)
        container.kill()
    sys.exit()
signal.signal(signal.SIGINT,handler)

# setup argparser to display help if no arguments
class ArgParser(argparse.ArgumentParser):
    def error(self,message):
        sys.stderr.write('error: %s\n' % message)
        self.print_help()
        sys.exit(2)

# determine command line arguments and get path
parser = ArgParser(description='Bacterial genome assembly and AR gene identification pipeline')
parser.add_argument('reads',type=str,help='text file listing the location of paired reads to be included in the analysis')
parser.add_argument('reference',type=str,help='text file listing the location of paired reads to be included in the analysis')
parser.add_argument('-o',metavar='output',type=str,help='output directory - defaults to working directory')
parser.add_argument('-t',metavar='threads',type=int,help='number of cpus to use for pipeline - default of 4',default=4)

args = parser.parse_args()

# common args
threads = args.t
reads_path = args.reads
ref = os.path.abspath(args.reference)
print(ref)

# get current working dir if output is empty
try:
    out = os.path.abspath(args.o)
except (AttributeError,TypeError) as err:
    out = os.getcwd()

# open file and pull locations into a list
with open(reads_path,'r') as f:
    r_list = []
    for line in f:
        if line.strip() != '':
            r_list.append(line.strip())

# sort and join pairs
r_list.sort()
if len(r_list) % 2 != 0:
    print('There is an uneven number of read pairs in the read list. Exiting.')
    sys.exit()
paired_reads = []
[paired_reads.append([x,y]) for x,y in zip(r_list[0::2],r_list[1::2])]

# get num of jobs and number of cpus per job
jobs,cpu_job = cpu_count(threads)

# initialize tracker
pipeline = 'spriggan'
tracker = ST()
outdir = tracker.initialize(out,pipeline)

spriggan_pipeline(paired_reads,ref,jobs,cpu_job,outdir,tracker)
